---
- name: config | Configuring RabbitMQ
  template:
    src: "{{ rabbitmq_config_file }}"
    dest: "/etc/rabbitmq/rabbitmq.config"
  become: true
  notify: "restart rabbitmq-server"
  tags:
    - configure

- name: config | Configuring RabbitMQ environemnt
  template:
    src: "{{ rabbitmq_config_env_file }}"
    dest: "/etc/rabbitmq/rabbitmq-env.conf"
  become: true
  notify: "restart rabbitmq-server"
  tags:
    - configure
