---
- name: redhat | installing pre-reqs
  yum:
    name: ['wget']
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | adding Erlang public GPG key
  rpm_key:
    key: "{{ erlang_redhat_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | downloading Erlang
  get_url:
    url: "{{ erlang_redhat_rpm_url }}"
    dest: "/opt/{{ erlang_redhat_rpm }}"
  become: true
  ignore_errors: True
  register: download_erlang_result

- name: redhat | downloading Erlang
  get_url:
    url: "{{ erlang_redhat_rpm_url_alt }}"
    dest: "/opt/{{ erlang_redhat_rpm }}"
  become: true
  when: download_erlang_result is failed

- name: redhat | installing Erlang
  yum:
    name: "/opt/{{ erlang_redhat_rpm }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | adding RabbitMQ public GPG key
  rpm_key:
    key: "{{ rabbitmq_redhat_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | downloading RabbitMQ
  get_url:
    url: "{{ rabbitmq_redhat_rpm_url }}"
    dest: "/opt/{{ rabbitmq_redhat_rpm }}"
  become: true

- name: redhat | installing RabbitMQ
  yum:
    name: "/opt/{{ rabbitmq_redhat_rpm }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | starting and enabling RabbitMQ service
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: true

- name: redhat | enabling the RabbitMQ Management Console
  rabbitmq_plugin:
    names: "{{ rabbitmq_enabled_plugins }}"
    state: enabled
    new_only: yes
  notify: restart rabbitmq-server
  become: true
